apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shop-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shop-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shop-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "shop-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "shop-operator.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEFAULT_SHOP_IMAGE
              value: {{ .Values.shopImage | quote }}
            - name: INGRESS_BASE_DOMAIN
              value: {{ .Values.ingress.baseDomain | quote }}
            - name: INGRESS_URL_PORT
              value: {{ .Values.ingress.urlPort | quote }}
          args:
            - --health-probe-bind-address=:8081
            {{- if .Values.metricsService.enabled }}
            - --metrics-bind-address=:{{ .Values.metricsService.port }}
            - --metrics-secure=false
            {{- end }}
            {{- if .Values.leaderElection }}
            - --leader-elect
            {{- end }}
          ports:
            - name: probe
              containerPort: 8081
              protocol: TCP
            {{- if .Values.metricsService.enabled }}
            - name: metrics
              containerPort: {{ .Values.metricsService.port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
